name: Java CI with Maven

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: "zulu"
          java-version: 21
          cache: "maven"

      - name: Build with Maven
        run: mvn --batch-mode --strict-checksums package

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@c950f6fb443cb5af20a377fd0dfaa78838901040 # v2.23.0
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Unit Test Results
          files: target/surefire-reports/**/*.xml
          report_individual_runs: true
          deduplicate_classes_by_file_name: false

      - name: Run SpotBugs from Maven
        run: mvn --batch-mode ${SPOTBUGS_PLUGIN} ${SPOTBUGS_OPTIONS}
        env:
          SPOTBUGS_PLUGIN: com.github.spotbugs:spotbugs-maven-plugin:spotbugs
          SPOTBUGS_OPTIONS: -Dspotbugs.xmlOutput=true -Dspotbugs.effort=max -Dspotbugs.threshold=low -Dspotbugs.failOnError=true

      - name: Publish SpotBugs report
        uses: jwgmeligmeyling/spotbugs-github-action@875e3b6fc5b97deadd8ea150948e53c2d40b13be # master
        if: ${{ github.actor != 'dependabot[bot]' }}        
        with:
          path: "**/spotbugsXml.xml"

      - name: Run Checkstyle from Maven
        run: mvn --batch-mode checkstyle:checkstyle

      - name: Publish Checkstyle report
        uses: jwgmeligmeyling/checkstyle-github-action@a12be500c097a5cedab881d4785ef9b4a4d3ee6a # master
        if: ${{ github.actor != 'dependabot[bot]' }}        
        with:
          path: "**/checkstyle-result.xml"

      - name: Run PMD from Maven
        run: mvn --batch-mode pmd:pmd pmd:cpd

      - name: Publish PMD reports
        uses: jwgmeligmeyling/pmd-github-action@1ad8208a5b2f710f350860e730ebe673e58666fa # master
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          path: "target/??d.xml"
